category: cepcsoft
subdir: EventDisplay
version: 01-07-02

dep: [GCC, CMake, CLHEP, GSL, ILCUTIL, LCIO, GEAR, Marlin, MarlinUtil, CED, LCCD]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libCEDViewer.so'

source:
  url: https://svnsrv.desy.de/public/marlinreco/CEDViewer/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
