category: cepcsoft
subdir: EventDisplay
version: '2.4'

dep: [GCC, LCIO, GEAR, ROOT]

location:
  source: ''
  build: 'src'
  install: ''

path:
  bin: '{install}/bin'

setenv:
  DRUIDDIR: '{install}'

source:
  url: http://cepcsoft.ihep.ac.cn/package/cepcsoft/Druid/{version}/Druid-{version}.tar.gz
  file: Druid-{version}.tar.gz
  main: Druid-{version}

build: [make]

install:
  download: http
  pre_compile: env
