category: cepcsoft
subdir: Reconstruction/HighLevelObjectFinding/Jets
version: 00-02

dep: [GCC, CMake, ROOT, ILCUTIL, Marlin, MarlinUtil, CLHEP, GEAR, GSL, LCIO, FastJet]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libFastJetClustering.so'

install:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/FastJetClustering/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
  clean:
    handler: clean
    param:
      dir: [build, download, log]
