category: cepcsoft
subdir: Reconstruction/PFA
version: 2.10.1

dep: [GCC, CMake, ROOT, ILCUTIL, LCIO, GEAR, Marlin, MarlinUtil]

path:
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libGarlic.so'

source:
  url: https://svnsrv.desy.de/public/Garlic/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
