category: cepcsoft
subdir: Service
version: 01-16-03

dep: [GCC, CMake, ROOT, ILCUTIL]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'

install:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/GeneralBrokenLines/tags/V{version}/cpp
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
  clean:
    handler: clean
    param:
      dir: [build, download, log]
