category: cepcsoft
subdir: Simulation
version: 01-04

dep: [GCC, CMake, CLHEP, ROOT, ILCUTIL]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'

install:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/gear/gear/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
        GEAR_TGEO: 'ON'
  clean:
    handler: clean
    param:
      dir: [build, download, log]
