category: cepcsoft
subdir: Reconstruction/Tracking
version: 01-04

dep: [GCC, CMake, ROOT, ILCUTIL, Marlin]

path:
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/marlinreco/KiTrack/tags/v{version}

patch: KiTrack-01-04.patch

build: [cmake, make, make_install]

install:
  download: svn
