category: cepcsoft
subdir: Reconstruction/HighLevelObjectFinding/Jets
version: 00-06-01

dep: [GCC, CMake, ILCUTIL, Marlin, MarlinUtil, LCIO, GEAR, RAIDA]

path:
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libLCFIVertex.so'

source:
  url: https://svnsrv.desy.de/public/marlinreco/LCFIVertex/tags/v{version}

cmake:
  var:
    AIDA: 'OFF'

build: [cmake, make, make_install]

install:
  download: svn
  pre_build:
    command:
      cmd: ['tar', '-xvf', 'boost.tgz']
