subdir: Framework
version: 02-04-03

dep: [GCC, CMake, CLHEP, ROOT, ILCUTIL]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'
  python: '{source}/src/python'

env:
  set_env:
    LCIO: '{install}'

source:
  url: svn://svn.freehep.org/lcio/tags/v{version}

cmake:
  var:
    BUILD_ROOTDICT: 'ON'
    INSTALL_JAR: 'OFF'
    LCIO_GENERATE_HEADERS: 'OFF'

build: [cmake, make, make_install]

install:
  download: svn
