category: cepcsoft
subdir: Reconstruction/Tracking
version: 01-10

dep: [GCC, CMake, ROOT, GSL, ILCUTIL, LCIO, Marlin, MarlinUtil, KalTest, KalDet, MarlinTrk, KiTrack, KiTrackMarlin, RAIDA]

path:
  lib: '{install}/lib'
  marlin: '{install}/lib/libMarlinTrkProcessors.so'

source:
  url: https://svnsrv.desy.de/public/marlinreco/MarlinTrkProcessors/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
