category: cepcsoft
subdir: Framework
version: 01-05

dep: [GCC, CMake, CLHEP, QT, ILCUTIL, LCIO, GEAR, LCCD, RAIDA]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/marlin/Marlin/tags/v{version}

cmake:
  var:
    MARLIN_GUI: 'OFF'

build: [cmake, make, make_install]

install:
  download: svn
