category: not_used
subdir: Simulation
version: 08-03_150612

dep: [GCC, CMake, Geant4, MySQL, HepMC, Boost, ILCUTIL, LCIO, GEAR]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  bin: '{install}/bin'
  lib: '{install}/lib'

install:
  download:
    handler: http
    param:
      url: http://cepcsoft.ihep.ac.cn/package/cepcsoft/Mokka/{version}/Mokka-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: Mokka-{version}.tar.gz
      main: Mokka-{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
  clean:
    handler: clean
    param:
      dir: [build, download, log]
