category: cepcsoft
subdir: Reconstruction/PFA/Pandora
version: 00-12

dep: [GCC, CMake, ROOT, ILCUTIL]

path:
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/PandoraPFANew/PandoraPFANew/tags/v{version}

cmake:
  var:
    PANDORA_MONITORING: 'OFF'

build: [cmake, make, make_install]

install:
  download: svn
