category: cepcsoft
subdir: Reconstruction/PFA/Pandora
version: 00-05

dep: [GCC, CMake, ROOT, ILCUTIL, Marlin, MarlinUtil, GEAR, LCIO]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libPandoraAnalysis.so'

source:
  url: https://svnsrv.desy.de/public/PandoraPFANew/PandoraAnalysis/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
