version: 2.06.08

dep: [GCC, CMake]

path:
  lib: '{install}/lib'
  inc: '{install}/include'
  cmake: '{install}'

source:
  url: http://lcgapp.cern.ch/project/simu/HepMC/download/HepMC-{version}.tar.gz

cmake:
  var:
    momentum: GEV
    length: MM

build: [cmake, make, make_install]

install:
  download: http
