version: 3.2.0

dep: [GCC]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'
  pkgconfig: '{install}/lib/pkgconfig'
  cmake: '{install}'

source:
  url: https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-{version}.tar.gz

configure:
  args: [--enable-transcoder-gnuiconv, --enable-msgloader-inmemory]

build: [configure, make, make_install]

install:
  download: http
